name: Push to EC2

on: workflow_dispatch

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Make env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_API_KEY: ${{ secrets.API_KEY }}
          envkey_WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          file_name: .env
          fail_on_empty: false

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
